# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

sass:
  sass_dir: _sass
  style: expanded # compressed # expanded

# permalink and highlighter
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

# SEO settings
title: Knox3DP
description: "Meetup in Knoxville, TN devoted to 3d printing and CAD"
keywords: "3d printing, Tennessee, Knoxville, CAD, additive manufacturing"

# Site settings
url: http://knox3dp.org
baseurl: ""
# baseurl: ""

# Author settings
author:
  name      : Alex Pawlowski
  job       : President
  bio       : "Triathlete, PhD student at UT, love to compete and enjoy every moment"
  thumb     : /images/author.jpg
  email     : organizer@knox3dp.org
  url       : http://knox3dp.org
  twitter   : https://twitter.com/knox3dp
  meetup    : http://www.meetup.com/knox3dp/
  #instagram : https://www.instagram.com/tntrivols/

google_analytics: UA-44543225-4
repo: http://github.com/knox3dp/knox3dp.github.io

# comments
disqus_shortname: "knox3dp"

gems:
  - github-pages
  - jekyll-sitemap
